name: DreamFlyPlugin
version: '${project.version}'
main: com.scarike.minecraft.DreamFlyPlugin
api-version: 1.18
authors: [ Scarike ]
description: DreamFly Sleepwalking Minecraft Spigot 1.18.1
commands:
  wakeup:
    description: 从梦境中唤醒自己
    usage: /wakeup
